from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
IMAGES_DIR = BASE_DIR / "images"

APP_TITLE = "Chiller System Operations Dashboard"
APP_ICON = "❄️"
LAYOUT = "wide"

FACILITY_NAME = "SEAGATE KORAT FACILITY"
FACILITY_SUBTITLE = "Chiller Operations Dashboard"

DEFAULT_TARGET_POWER_TON = 0.75
MIN_TARGET_POWER_TON = 0.10
MAX_TARGET_POWER_TON = 2.00

COND_APPROACH_WARNING_F = 5.0
COND_APPROACH_CRITICAL_F = 7.0
EVAP_APPROACH_WARNING_F = 5.0
EVAP_APPROACH_CRITICAL_F = 7.0
KWRT_WARNING_DELTA = 0.10
KWRT_CRITICAL_DELTA = 0.20

DEFAULT_DATA_FILE = str(BASE_DIR / "sample_data.csv")
SEAGATE_LOGO_PATH = str(IMAGES_DIR / "seagate_logo.png")
CHILLER_IMAGE_PATH = str(IMAGES_DIR / "chiller.png")
COOLING_TOWER_IMAGE_PATH = str(IMAGES_DIR / "cooling_tower.png")
CONDENSER_PUMP_IMAGE_PATH = str(IMAGES_DIR / "condenser_pump.png")
CHILLED_PUMP_IMAGE_PATH = str(IMAGES_DIR / "chilled_pump.png")

STATUS_NORMAL = "Normal"
STATUS_CHECK = "Check"
STATUS_WARNING = "Warning"
STATUS_CRITICAL = "Critical"
STATUS_ALERT_VALUES = {STATUS_CHECK, STATUS_WARNING, STATUS_CRITICAL}

EQUIPMENT_CHILLER = "Chiller"
EQUIPMENT_COOLING_TOWER = "Cooling Tower"
EQUIPMENT_CONDENSER_PUMP = "Condenser Pump"
EQUIPMENT_CHILLED_PUMP = "Chilled Pump"

LOGO_WIDTH_SIDEBAR = 90
LOGO_WIDTH_HEADER = 110
EQUIPMENT_CARD_WIDTH = 110

BUILDING_NAMES = [
    "Building A",
    "Building B",
    "Building C",
    "Building D",
    "Building E",
    "Building F",
]

DETAIL_PAGE_MAP = {
    EQUIPMENT_CHILLER: "pages/4_Chiller_Detail.py",
    EQUIPMENT_COOLING_TOWER: "pages/5_Cooling_Tower_Detail.py",
    EQUIPMENT_CONDENSER_PUMP: "pages/6_Condenser_Pump_Detail.py",
    EQUIPMENT_CHILLED_PUMP: "pages/7_Chilled_Pump_Detail.py",
}

EQUIPMENT_IMAGE_MAP = {
    EQUIPMENT_CHILLER: CHILLER_IMAGE_PATH,
    EQUIPMENT_COOLING_TOWER: COOLING_TOWER_IMAGE_PATH,
    EQUIPMENT_CONDENSER_PUMP: CONDENSER_PUMP_IMAGE_PATH,
    EQUIPMENT_CHILLED_PUMP: CHILLED_PUMP_IMAGE_PATH,
}
